api_platform:
    title: My test api platform
    version: 1.0.0
    defaults:
        #stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]  # Enables plain JSON for input/output
